repository:
  description: Default Description set by probot/settings
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: master
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: ['Semantic Pull Request']
      enforce_admins: true
      restrictions: null
