repository:
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: master
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
labels:
  - name: auto-merge
    color: E2BD73
    description: Triggers probot-auto-merge to merge PRs https://github.com/bobvanderlinden/probot-auto-merge#probot-auto-merge
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: ['Semantic Pull Request', 'WIP']
      enforce_admins: true
      restrictions: null
